name: UI Linting and Formatting

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ui/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ui/**'
  workflow_dispatch:

jobs:
  lint-and-format:
    name: Lint and Format UI Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Build project (smoke test)
        run: npm run build